import localFont from "next/font/local";
import "./globals.css";
import { RakshakProvider } from "@/contexts/RakshakContext";
import { RakshakSupplyProvider } from "@/contexts/RakshakSupplyContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RakshakProvider>
      <RakshakSupplyProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-secondary`}
      >
        {children}
      </body>
    </html>
      </RakshakSupplyProvider>
    
    </RakshakProvider>
    
  );
}
